project_id = "gfsbsgwxylvhnwbpcodj"

[functions]
  [functions.admin-sync-stripe]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.notify-order-status]
    verify_jwt = false
