project_id = "gfsbsgwxylvhnwbpcodj"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.admin-sync-stripe]
verify_jwt = false